---
title: "Acd_Am-Dmax"
author: "Balam"
date: "2023-10-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
getwd()
setwd("/home/sdv/m1isdd/gbalamtekin/Documents/Projet_asymetrie_Biostat/")
```

```{r}
dfb1AC6 <- read.table("DATA/Dmax/Asymetry/1AC6_AB_distanceMax_backbone_byRes.txt", header = TRUE)
df1AC6 <- read.table("DATA/Dmax/Asymetry/1AC6_AB_distanceMax_byRes.txt", header = TRUE)

hist(dfb1AC6$distance_max_interChain[grepl("ALA", dfb1AC6$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AC6$distance_max_interChain[grepl("ALA", df1AC6$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AC6$distance_max_interChain[grepl("GLY", dfb1AC6$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AC6$distance_max_interChain[grepl("GLY", df1AC6$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AC6$distance_max_interChain[grepl("ARG", dfb1AC6$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AC6$distance_max_interChain[grepl("ARG", df1AC6$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AC6$distance_max_interChain[grepl("GLU", dfb1AC6$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AC6$distance_max_interChain[grepl("GLU", df1AC6$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AC6$distance_max_interChain[grepl("TYR", dfb1AC6$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AC6$distance_max_interChain[grepl("TYR", df1AC6$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AC6$distance_max_interChain[grepl("LYS", dfb1AC6$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AC6$distance_max_interChain[grepl("LYS", df1AC6$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AC6$distance_max_interChain[grepl("ASP", dfb1AC6$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AC6$distance_max_interChain[grepl("ASP", df1AC6$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AC6$distance_max_interChain[grepl("CYS", dfb1AC6$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AC6$distance_max_interChain[grepl("CYS", df1AC6$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AC6$distance_max_interChain[grepl("PHE", dfb1AC6$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AC6$distance_max_interChain[grepl("PHE", df1AC6$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AC6$distance_max_interChain[grepl("LEU", dfb1AC6$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AC6$distance_max_interChain[grepl("LEU", df1AC6$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AC6$distance_max_interChain[grepl("ILE", dfb1AC6$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AC6$distance_max_interChain[grepl("ILE", df1AC6$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AC6$distance_max_interChain[grepl("VAL", dfb1AC6$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AC6$distance_max_interChain[grepl("VAL", df1AC6$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AC6$distance_max_interChain[grepl("PRO", dfb1AC6$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AC6$distance_max_interChain[grepl("PRO", df1AC6$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AC6$distance_max_interChain[grepl("SER", dfb1AC6$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AC6$distance_max_interChain[grepl("SER", df1AC6$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AC6$distance_max_interChain[grepl("ASN", dfb1AC6$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AC6$distance_max_interChain[grepl("ASN", df1AC6$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AC6$distance_max_interChain[grepl("GLN", dfb1AC6$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AC6$distance_max_interChain[grepl("GLN", df1AC6$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AC6$distance_max_interChain[grepl("THR", dfb1AC6$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AC6$distance_max_interChain[grepl("THR", df1AC6$atom_nm)], breaks = 20, col = "red", add = TRUE)
```

```{r}
dfb1AIZ <- read.table("DATA/Dmax/Asymetry/1AIZ_AB_distanceMax_backbone_byRes.txt", header = TRUE)
df1AIZ <- read.table("DATA/Dmax/Asymetry/1AIZ_AB_distanceMax_byRes.txt", header = TRUE)

hist(dfb1AIZ$distance_max_interChain[grepl("ALA", dfb1AIZ$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AIZ$distance_max_interChain[grepl("ALA", df1AIZ$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AIZ$distance_max_interChain[grepl("GLY", dfb1AIZ$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AIZ$distance_max_interChain[grepl("GLY", df1AIZ$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AIZ$distance_max_interChain[grepl("ARG", dfb1AIZ$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AIZ$distance_max_interChain[grepl("ARG", df1AIZ$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AIZ$distance_max_interChain[grepl("GLU", dfb1AIZ$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AIZ$distance_max_interChain[grepl("GLU", df1AIZ$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AIZ$distance_max_interChain[grepl("TYR", dfb1AIZ$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AIZ$distance_max_interChain[grepl("TYR", df1AIZ$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AIZ$distance_max_interChain[grepl("LYS", dfb1AIZ$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AIZ$distance_max_interChain[grepl("LYS", df1AIZ$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AIZ$distance_max_interChain[grepl("ASP", dfb1AIZ$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AIZ$distance_max_interChain[grepl("ASP", df1AIZ$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AIZ$distance_max_interChain[grepl("CYS", dfb1AIZ$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AIZ$distance_max_interChain[grepl("CYS", df1AIZ$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AIZ$distance_max_interChain[grepl("PHE", dfb1AIZ$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AIZ$distance_max_interChain[grepl("PHE", df1AIZ$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AIZ$distance_max_interChain[grepl("LEU", dfb1AIZ$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AIZ$distance_max_interChain[grepl("LEU", df1AIZ$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AIZ$distance_max_interChain[grepl("ILE", dfb1AIZ$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AIZ$distance_max_interChain[grepl("ILE", df1AIZ$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AIZ$distance_max_interChain[grepl("VAL", dfb1AIZ$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AIZ$distance_max_interChain[grepl("VAL", df1AIZ$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AIZ$distance_max_interChain[grepl("PRO", dfb1AIZ$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AIZ$distance_max_interChain[grepl("PRO", df1AIZ$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AIZ$distance_max_interChain[grepl("SER", dfb1AIZ$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AIZ$distance_max_interChain[grepl("SER", df1AIZ$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AIZ$distance_max_interChain[grepl("ASN", dfb1AIZ$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AIZ$distance_max_interChain[grepl("ASN", df1AIZ$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AIZ$distance_max_interChain[grepl("GLN", dfb1AIZ$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AIZ$distance_max_interChain[grepl("GLN", df1AIZ$atom_nm)], breaks = 20, col = "red", add = TRUE)

hist(dfb1AIZ$distance_max_interChain[grepl("THR", dfb1AIZ$atom_nm)], breaks = 20, col = "blue", main = "Superposed Histograms")
hist(df1AIZ$distance_max_interChain[grepl("THR", df1AIZ$atom_nm)], breaks = 20, col = "red", add = TRUE)
```

```{r}
data <- read.table("DATA/Dmax/distMax_alldimers.txt", header = TRUE)

noms_des_variables <- colnames(data)

for (variable in noms_des_variables) {
  if (variable != "distance_max_interChain") {
    test_result <- cor.test(data[,"distance_max_interChain"], data[,variable], method = "pearson")
    if ((test_result$p.value < 0.05) & (test_result$estimate > 0.5)) {
      cat("Variable:", variable, "\n")
      cat("Correlation Estimate:", test_result$estimate, "\n")
      cat("P-Value:", test_result$p.value, "\n")
    }
  }
}

```

